[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Plugins configuration
addopts =
    --html=reports/html/report.html
    --self-contained-html
    --json-report
    --json-report-file=reports/json/report.json
    -v
    --strict-markers

markers =
    api: API tests
    database: Database tests
    logs: Log validation tests
    slow: slow tests
    integration: integration tests
